### ISSUE TITLE
.infobot memes doesn't work

### ISSUE THREAD

**Issue by alexismartin** [joseph-galindo/condor-tune-infobot#4]
.infobot memes shows `Sorry, I don't understand that command. For a list of commands I understand, try .infobot help.` and no memes at all.

**Comment by joseph-galindo** [comment]
@alexismartin I will be adding in this functionality asap

**Comment by joseph-galindo** [comment]
Functionality now in since commit f69e190b2d930ab91bc3aa98cf5cba719afb1a0a, closing this issue
